### ISSUE TITLE
Add support for ::placeholder

### ISSUE THREAD

**Issue by nsimonson** [rofrischmann/inline-style-prefixer#104]
Only Firefox 51 currently supports this pseudo element unprefixed.
https://css-tricks.com/snippets/css/style-placeholder-text/

**Comment by rofrischmann** [comment]
I am still sceptical if this repo really is the "right" place to add sth. like this as it can be used for inline styles which do not support pseudo classes at all.

On the other hand this repo is used heavily by css-in-js solutions supporting pseudo classes or even compiling to CSS.

**Comment by nsimonson** [comment]
I've been thinking about that as well. I wasn't sure who's responsibility this falls too. We are using this library via aphrodite. It seems like this library would solely responsible for prefixing properties and the css-in-js authors would need to handle odd cases like psuedo-elements/classes. I've opened a separate issue with them. 

https://github.com/Khan/aphrodite/issues/171

**Comment by rofrischmann** [comment]
Yet, it is the only pseudo class I know that needs prefixing like this one. All other prefixed placeholders are non standard and therefor only exist with prefixes.
It's just like e.g. `WebkitFontSmoothing` or `MozOsxFontSmoothing`. They are not standard as there is no `font-smoothing` which is why we do not support it either. (I have to do a can-i-use map update anyways, maybe some new stuff gets added in soon)

**Comment by rofrischmann** [comment]
Will close this as we won't add it to the core too soon.
