### ISSUE TITLE
Hard-code caniuse.com data

### ISSUE THREAD

**Issue by necolas** [rofrischmann/inline-style-prefixer#11]
Hard-coding it avoids the post-install step and provides a better guarantee of correctness in the installed environment. I'd be a bit concerned about the data being fetched (and potentially changing) every CI run.

**Comment by ianobermiller** [comment]
Hmm, I tend to agree here. Keep the data generation script, of course, but just run it periodically to update the data instead of on install. Downside is that it needs to be periodically updated, and someone needs to maintain the project. But not a huge deal, since that is usually the case for prefixing libraries.

**Comment by rofrischmann** [comment]
This sounds fine. Had so many struggle to even get the CI-builds runnin correctly 😅 
I will add that later on as I am also trying to create a better way to define those small special hacks.

Thanks for investigating guys :)
