### ISSUE TITLE
Best way to support newer browsers

### ISSUE THREAD

**Issue by jgraniero** [rofrischmann/inline-style-prefixer#152]
I have a style rule with `boxDecorationBreak` and I'm not seeing any prefix for that on Chrome 63, so the rule isn't working.

I looked through the code quickly and saw that in `dynamicData.js`, `boxDecorationBreak` is mapped to chrome version 62 and since I'm on 63, the prefixer isn't adding the necessary prefix.

Is there a quick way to work around this without using the static prefixer (which is definitely an option, but would prefer to use the dynamic prefixer if possible)?

**Comment by rofrischmann** [comment]
Actually, it'd make sense to check for a minimum browser version instead of a fixed maximum version. I need to figure that out though, as it would break all the other use cases as is. 

Currently, I am away with my orchestra, which means I'm not doing anything this weekend. Let me check that next week.

**Comment by rofrischmann** [comment]
I just updated the versions to match newest browsers, we might consider having an automated release whenever caniuse browser versions change, but if I consider that, I'd open a separate issue so ill close this one now :P
