### ISSUE TITLE
Can't detect the useragent of Cordova apps.

### ISSUE THREAD

**Issue by iseki-masaya** [rofrischmann/inline-style-prefixer#40]
This issue is related to https://github.com/callemall/material-ui/issues/2692 .

'inline-style-prefixer' can't detect the useragent of Cordova apps.

```
// iOS 8.4.1 Safari
Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4
```

```
// iOS 8.4.1 Cordova app
Mozilla/5.0 (iPhone; CPU iPhone OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4
```

Tested on:

iOS 8.4.1
Cordova CLI 5.4.1
Cordova iOS 4.0.0 (WKWebView and UIWebView)

**Comment by rofrischmann** [comment]
I will check that soon. I think it got nothing todo with Cordova at all (as I am using the library with Cordova too). It's rather again a problem with the browser detection library the prefixer is built on as both the userAgents seem to be identically.

**Comment by iseki-masaya** [comment]
@rofrischmann Thank you for your reply. I will also check this file (https://github.com/callemall/material-ui/blob/master/src/styles/auto-prefix.js).

**Comment by alexdrel** [comment]
Hi, I have same problem on IOS 8 (and it seems many other judging by material-ui issues), IOS 9 is fine.
 
My userAgent on Cordova differs:
```Mozilla/5.0 (iPad; CPU OS 8_4 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12H141 (140618339105120)```
The version is missing - it looks like a known bug as ```bowser``` have special case for it and a comment.

I think that the problem is with the following line
```info.version = parseFloat(info.version)```
it produces ```NaN```.
Changing it to 
```  info.version = info.version ? parseFloat(info.version) : 0;```
Fixes it for me.
I also tried to use osversion when version is missing but it is not good as caniuse seemingly use 8.1 as cut point for ios.

**Comment by harumando** [comment]
Hi, i don't know if you fixed this or not, but on blackberry cordova app i'm getting a warning that my browser in not supported by the plugin.

My user agent is - "Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.2.281 Mobile Safari/537.35+"

Also material-ui seems to be not working properly because i don't have -webkit- prefix on several styles.

**Comment by rofrischmann** [comment]
Hey @harumando, actually I don't think we will ever really support Blackberry nor Phonegap, but the new fallback comes to rescue.

With 1.0 the prefixer will fallback to prefixAll which adds every fallback, so you should be save using that.
