### ISSUE TITLE
Invalid failover values

### ISSUE THREAD

**Issue by priezz** [rofrischmann/inline-style-prefixer#91]
Hi there!

First of all thanks for a nice product (I mean Fela, of course)! It is not so easy to use as some other competitors, but seems to be more extensible and feature rich, so after the long comparison I have decided to is it as a primary styling tool :)

I have found, that properties like `width: -webkit-calc(33.3% - 20px),-moz-calc(33.3% - 20px),calc(33.3% - 20px);` are not accepted by Yandex Browser, which is Chromium based. I have checked in the latest dev Chrome - the same thing. So I believe, it would be better, to provide fallbacks more traditional way:
```
width: -moz-calc(33.3% - 20px);
width: -webkit-calc(33.3% - 20px);
width: calc(33.3% - 20px);
```

Actually, the `fallbackValue` plugin already does it this way, so I hope it could be reused easily.

**Comment by rofrischmann** [comment]
Hey @priezz. First of all thanks for your kind words. Also feel free to tell me with which parts you struggled, so I can improve usage guides etc.
This library returns arrays with fallback values, because it can also be used with inline style solutions. Sadly inline solutions can not use fallback strings e.g. `{ display: '-webkit-flex;display:flex' }` (at least if you're working with React 15+). Thats why we decided to return arrays so each library can decide on their own if they rather like to transform to CSS (and do what you described above) or validate each value (e.g. by testing out with a DOM element) and to just the first one that is supported. 

We might need to add this to the documentations here as else you can not use the prefixer with CSS as it is. But as you pointed out, if you're going with Fela you can just use the `fallbackValue` plugin afterwards :P

**Comment by priezz** [comment]
So, do I understand right that both `prefixer` and `dynamicPrefixer` are not usable at the moment? What is the recommended approach? To fork one of these plugins and switch it into `fallbackValue`'s behaviour?

**Comment by rofrischmann** [comment]
Oh nono, you can use both of course :P You only need the fallbackValue to resolve arrays. I just wanted to say you can not use this lib without using one of the solutions listed above (either resolve arrays & transform to CSS or validate values). But this has nothing to do with Fela directly as the fallbackValue does the resolving automatically.

**Comment by priezz** [comment]
Well, then please advice, how to do it :)  I create the renderer this way:
```
const stylesRenderer = createRenderer({
    plugins: [
        friendlyPseudoClass(),
        extend(),
        fallbackValue(),
        dynamicPrefixer({
            userAgent: navigator.userAgent,
            keepUnprefixed: true,
        }),
        unit( "px" ),
        validator(),
    ],
    enhancers: [
        fontRenderer( fontsContainer ),
    ]
})
```

**Comment by rofrischmann** [comment]
I guess you just need to switch the `dynamicPrefixer` and the `fallbackValue`. As pointed out [here](https://github.com/rofrischmann/fela/tree/master/packages/fela-plugin-dynamic-prefixer) fallbackValue **must** run after the prefixer :P

**Comment by priezz** [comment]
Oh, thanks! I have seen this warning but for some reason thought that they just have to be used together. Maybe it will be useful to provide the example below this note :)

**Comment by rofrischmann** [comment]
Yeah right. I am always happy with feedback how to improve the documentations, thank you :) I will close this one right? If you got any questions please catch me on Gitter, either private oder at the Fela channel :P

**Comment by priezz** [comment]
As for my experience with Fela and the enhancement (very few) I have made - where it it better to write to? To your email or to the Fela's issues?
